Add POST/articles/:article_id/comments
gwdawson/northcoders-news-api pull request #9
Opened 2022-03-31 08:59 UTC by gwdawson

2022-03-31 09:45 UTC, karlaferry requested changes
Looks good! If you would please do the error handling and resubmit for approval that would be great. 😄

2022-04-01 10:14 UTC, karlaferry approved these changes
⬇️⬇️⬇️

2022-04-01 10:15 UTC, karlaferry requested changes
Actually, I don't see any error handling! Have you done any?

2022-04-01 10:50 UTC, gwdawson commented on __tests__/articles.test.js
> +      const { body } = await request(app)
i like the suggestion but unfortunately prettier formats it so it look more confusing.

2022-04-01 11:31 UTC, jadelandeg commented on __tests__/articles.test.js
> +
nice! Still need more error handling though, what could go wrong with the article id?

2022-04-01 11:31 UTC, jadelandeg requested changes
more error handling please

2022-04-01 15:30 UTC, dentednerd approved these changes
Great work Gareth!

2022-04-01 15:31 UTC, merged